name: 'duck_dbt'
version: '1.0.0'
profile: 'duck_dbt'

# Paths for your DBT project artifacts
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean targets
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  duck_dbt:
    staging:
      +materialized: view         # default for staging
      sf_crime_raw:
        +materialized: table      # override landing/raw CSV mirror
    marts:
      +materialized: table        # default for all marts (weekly/monthly)